# Generated by Django 3.0.8 on 2020-07-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='hola', max_length=200),
            preserve_default=False,
        ),
    ]
